name: scrape

on:
  push:
    branches:
      - master

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.23.4
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: Install dependencies
        run: go mod download

      - name: Run scraper
        run: go run main.go -maxParagraphs 2000

      - name: Upload scraped data
        uses: actions/upload-artifact@v4
        with:
          name: scraped-data
          path: data.csv

